rd %~p1%Inlumino_UAP\Content\bin /s /q
rd %~p1%Inlumino_UAP\Content\obj /s /q
rd %~p1%Inlumino_UAP\bin /s /q
rd %~p1%Inlumino_UAP\obj /s /q
rd %~p1%Inlumino_ANDROID\Content\bin /s /q
rd %~p1%Inlumino_ANDROID\Content\obj /s /q
rd %~p1%Inlumino_ANDROID\bin /s /q
rd %~p1%Inlumino_ANDROID\obj /s /q
rd %~p1%ConvertToXNAContent\bin /s /q
rd %~p1%ConvertToXNAContent\obj /s /q